SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER PROCEDURE ONBOARDING.USER_BY_ID_GET (@USER_ID VARCHAR(100))

AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	SELECT * FROM USERS (NOLOCK) WHERE ID = @USER_ID

END
GO