SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER PROCEDURE ONBOARDING.USERS_INS (@NAME VARCHAR(150), @EMAIL VARCHAR(100), @PASSWORD VARCHAR(100))

AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	INSERT INTO USERS VALUES(NEWID(), @NAME, @EMAIL, @PASSWORD, GETDATE())

END
GO
