SET
    ANSI_NULLS ON
GO
SET
    QUOTED_IDENTIFIER ON
GO
    CREATE
    OR ALTER PROCEDURE [ONBOARDING].[USER_DEL] (@ID VARCHAR(50)) AS BEGIN -- SET NOCOUNT ON ADDED TO PREVENT EXTRA RESULT SETS FROM
    -- INTERFERING WITH SELECT STATEMENTS.
SET
    NOCOUNT ON;

DELETE USERS
WHERE
    ID = @ID
END
GO